services:
  db:
    image: postgres:18
    container_name: mail_helper_db
    environment:
      POSTGRES_USER: mail_bot
      POSTGRES_PASSWORD: mail_bot_pass
      POSTGRES_DB: mail_helper
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mail_bot -d mail_helper"]
      interval: 5s
      timeout: 5s
      retries: 10

  logger:
    image: golang:1.21-alpine
    container_name: mail_helper_logger
    volumes:
      - ./cmd/log_server:/app
      - ./logs:/logs
    working_dir: /app
    command: go run main.go
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mail_helper_app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      logger:
        condition: service_healthy
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "echo 'Waiting for services...';
             while ! nc -z db 5432; do sleep 1; done;
             while ! nc -z logger 8081; do sleep 1; done;
             echo 'All services are up! Starting app...';
             go run ./cmd/main.go"
    ports:
      - "8080:8080"
    tty: true

volumes:
  pgdata:
